medicationDB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("patients/", include("patients.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("", TemplateView.as_view(template_name="home.html"), name="home"),
]

patients/urls.py
from django.urls import path
from . import views

app_name = 'patients'
urlpatterns = [
    path("", views.IndexView.as_view(), name='index'),
    path("<int:pk>/", views.DetailView.as_view(), name='detail'),
]

patients/models.py
from django.contrib import admin
from django.db import models
from django.utils import timezone
from django.contrib.auth import get_user_model
User = get_user_model()


# Create your models here.
class Prescription(models.Model):
    prescription_text = models.CharField(max_length=100)
    user = models.ForeignKey(User, models.CASCADE, default=1)
    creation_date = models.DateTimeField('date created')
    expiration_date = models.DateTimeField('date expired')

    class Meta:
        ordering = ['-creation_date']

    def __str__(self):
        return self.prescription_text

    @admin.display(
        boolean=True,
        ordering='creation_date',
        description='Valid?'
    )
    def is_valid(self):
        now = timezone.now()
        return now <= self.expiration_date


class MedicationName(models.Model):
    medication_name = models.CharField(max_length=100)

    class Meta:
        ordering = ['medication_name']

    def __str__(self):
        return self.medication_name


class Medication(models.Model):
    chosen_medication = models.ForeignKey(MedicationName, on_delete=models.PROTECT)
    medication_dose = models.CharField(max_length=100, default='None')
    prescription = models.ForeignKey(Prescription, on_delete=models.CASCADE)

    class Meta:
        ordering = ['chosen_medication']

    def __str__(self):
        return self.chosen_medication.medication_name

patients/views.py
from django.db.models import F
from django.http import HttpResponseRedirect, request
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.views.decorators.cache import never_cache
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from .models import Medication, Prescription

# Create your views here.
decorators = [never_cache, login_required]


@method_decorator(login_required, name='dispatch')
class IndexView(generic.ListView):
    template_name = 'patients/index.html'
    context_object_name = 'prescription_list'

    def get_queryset(self):
        # Will display the prescriptions of the user
        active_user = self.request.user.id
        return Prescription.objects.filter(creation_date__lte=timezone.now(),
                                           user=active_user).order_by('-creation_date')


@method_decorator(login_required, name='dispatch')
class DetailView(generic.DetailView):
    model = Prescription
    template_name = 'patients/detail.html'

    def get_queryset(self):
        # removes un published questions
        return Prescription.objects.order_by("-creation_date")

patients/templates/patients/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Prescription's detail</title>
    <link rel="stylesheet" href="{% static 'patients/style.css' %}">
</head>

<body>
    <div id='top_page_links'>
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'patients:index' %}">Prescriptions</a>
    </div>

    <div id="medication_box">
        <h2>Medication prescribed in: {{ prescription.prescription_text }}</h2>
        <p>This page will display a list of medications assigned to the selected prescription.</p>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% if prescription.medication_set.all %}
        <table>
            <tr>
                <th>Medication</th>
                <th>Dosage</th>
            </tr>
            {% for medication in prescription.medication_set.all %}
                <tr>
                    <td>{{ medication.chosen_medication }}</td>
                    <td>{{ medication.medication_dose }}</td>
                </tr>
            {% endfor %}
        </table>
        {% else %}
            <p>No medication registered in this prescription.</p>
        {% endif %}
    </div>
</body>
</html>

patients/templates/patients/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Patients' Index</title>
    <link rel="stylesheet" href="{% static 'patients/style.css' %}">
</head>
<body>
    <div id='top_page_links'>
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'patients:index' %}">Prescriptions</a>
    </div>
    <div id="prescription_box">
        <h2>{{ user.get_username }}'s prescriptions</h2>
        <p>Here is the section where users only see prescription assigned to their accounts.</p>
        {% if prescription_list %}
            <ul>
            {% for prescription in prescription_list %}
                <li><a href="{% url 'patients:detail' prescription.id %}">{{ prescription.prescription_text }}</a></li>
            {% endfor %}
            </ul>
        {% else %}
            <p>No prescriptions are available.</p>
        {% endif %}
    </div>
</body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Authentication base{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'styleProject.css' %}">
</head>
<body>
    <div id='top_page_links'>
        <a href="{% url 'home' %}">Home</a>
        <a href="{% url 'patients:index' %}">Prescriptions</a>
    </div>
    <main id="main_text">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated %}
    <h2>Hi {{ user.username }}!</h2>
    <p>Home page where the user can log in or log out</p>
    <div>
        <form action="{% url 'logout' %}" method="post">
        {% csrf_token %}
         <button type="submit">Log Out</button>
        </form>
    </div>
{% else %}
    <p>You are not logged in</p>
    <a href="{% url 'login' %}">Log In</a>
{% endif %}
{% endblock %}